<a href="https://colab.research.google.com/github/vedadapa/ml_foundations/blob/main/lInear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectors



*   DIFFERENTIATION IDENTIFICATION
*   FOR MOVIES



In [ ]:
import numpy as np

# Two movies as vectors
movie_a = np.array([8, 2, 4])
movie_b = np.array([7, 3, 5])
movie_c = np.array([1, 9, 2])  # romantic film, very different

# Distance between vectors
# Closer distance = more similar
dist_ab = np.linalg.norm(movie_a - movie_b)
dist_ac = np.linalg.norm(movie_a - movie_c)

print(f"Distance A to B: {dist_ab:.2f}")
print(f"Distance A to C: {dist_ac:.2f}")

# Which movie is more similar to movie A?
if dist_ab < dist_ac:
    print("Movie B is more similar to A")
else:
    print("Movie C is more similar to A")

Distance A to B: 1.73
Distance A to C: 10.10
Movie B is more similar to A


In [ ]:
movie_matrix = np.array([[8,2,4],
 [7, 3, 5],
  [1,2,9]])
shape = np.shape(movie_matrix)

print(shape)


(3, 3)


# NUMPY MODIFICATIONS


*   ROW MATRIX
*   COLUMN MATRIX
*   SLICED COLUMNS
*   ADDITION MATRIX






In [ ]:
row = movie_matrix[0]
print(row)


[8 2 4]


In [ ]:
col = movie_matrix[:,0]
print(col)

[9 8 2]


In [ ]:
col = movie_matrix[:,0]
print(col)

[[ 9  3  5]
 [ 8  4  6]
 [ 2  3 10]]


# COMPARISION OF 2 FEATURES AND FINDING THE SIMILARITY

*   COSINE_SIM - NORMALIZATION OF THE DOT PRODUCT

*   DOT PRODUCT - FINDING THE HIGH SIMILARITY





In [ ]:
import numpy as np
from numpy.linalg import norm
vector1 = np.array([9,2,4])
vector2 = np.array([9,7,2])
cosine_sim = np.dot(vector1,vector2)/(norm(vector1) * norm(vector2))
print("similarity:",cosine_sim)

similarity: 0.8853686472286518


#  EIGNVECTORS AND EIGNVALUES



*   COVARIANCE MATRIX - RELATION BETWEEN A ARRAY OF VALUES
*   USING TRANSPOSE- ROWS



In [ ]:

import numpy as np

# Imagine this is a small dataset - 3 documents, 3 features
data = np.array([
    [8, 2, 4],
    [7, 3, 5],
    [1, 9, 2]
])

# Covariance matrix - how features relate to each other
cov_matrix = np.cov(data.T)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:", eigenvalues)
print("Biggest eigenvalue index:", np.argmax(eigenvalues))

Eigenvalues: [ 3.05582203e+01 -3.13840154e-16  4.41779654e-01]
Biggest eigenvalue index: 0
